llm_type: 'openai' # 'openai', 'ollama', 'hf' or 'azure'
llm_name: 'gpt-4-turbo' # 'gpt-3.5-turbo', "llama3"

relevance_score_fn: 'l2'
k: 20
search_type: 'similarity'
score_threshold: 0.5
fetch_k: 20
lambda_mult: 0.5

embeddings_model_type: 'ollama' # 'openai', 'ollama', 'hf' or 'azure'
embeddings_model_name: 'nomic-embed-text' # 'text-embedding-ada-002', 'nomic-embed-text'

docs_db_directory: './db-docs'
docs_db_collection: 'garnet'
questions_db_directory: './db-questions'
questions_db_collection: 'questions_store'
